#include "PlayerController.h"
PlayerController playerController;
AudioPlayer audioPlayer;
void PlayerController::begin(){Serial.begin(115200);delay(500);Serial.println();Serial.println("--- ESP32 MP3 Player v2 ---");display.begin();sdSpi.begin(Config::SD_SPI_SCK,Config::SD_SPI_MISO,Config::SD_SPI_MOSI,Config::SD_SPI_CS);if(!SD.begin(Config::SD_SPI_CS,sdSpi,Config::SD_FREQUENCY)){Serial.println("SD initialisation failed");state=PlayerState::Error;display.showError("SD card failed");return;}Serial.println("SD working");audioPlayer.begin();if(!playlist.load()){Serial.println("Could not open /library");state=PlayerState::Error;display.showError("Library not found");return;}if(playlist.empty()){state=PlayerState::Error;display.showNoTracks();return;}encoder.begin();input.begin();randomSeed(esp_random());ready=true;playRandomTrack();}
void PlayerController::update(){if(!ready)return;audioPlayer.update();handleEnd();handleEncoder();handleButton(input.update());}
void PlayerController::playTrack(int i){const Track* t=playlist.get(i);if(!t)return;currentTrack=i;state=PlayerState::Playing;audioPlayer.play(t->path);refreshDisplay();}
void PlayerController::playRandomTrack(){int n=playlist.randomIndexExcept(currentTrack);if(n>=0)playTrack(n);}
void PlayerController::handleEnd(){if(audioPlayer.consumeTrackEnded())playRandomTrack();}
void PlayerController::handleEncoder(){if(state==PlayerState::Menu)return;int c=encoder.consumeClicks();if(!c)return;audioPlayer.setVolume(audioPlayer.getVolume()+c);Serial.print("Volume: ");Serial.println(audioPlayer.getVolume());refreshDisplay();}
void PlayerController::handleButton(ButtonEvent e){switch(e){case ButtonEvent::SingleClick:if(state==PlayerState::Menu){state=audioPlayer.isPaused()?PlayerState::Paused:PlayerState::Playing;refreshDisplay();}else{audioPlayer.togglePause();state=audioPlayer.isPaused()?PlayerState::Paused:PlayerState::Playing;Serial.println(audioPlayer.isPaused()?"Paused":"Playing");refreshDisplay();}break;case ButtonEvent::DoubleClick:if(state!=PlayerState::Menu){playRandomTrack();Serial.println("Skipped to random track");}break;case ButtonEvent::LongPress:state=PlayerState::Menu;display.showMenu();break;default:break;}}
void PlayerController::refreshDisplay(){const Track* t=playlist.get(currentTrack);if(t)display.showNowPlaying(t->path,currentTrack+1,playlist.size(),state,audioPlayer.getVolume());}
